import Head from 'next/head'

import HomePage from './HomePage'

export default function Home({data}) {
  console.log(data)
  
  return (
    <div>
      <Head>
        <title>musica app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <HomePage />
    </div>
  )
}

export async function getStaticProps() {
  const res = await fetch("https://musica-api.up.railway.app/new")
  const data = await res.json()
  return {
    props: {
      data,
    }, // will be passed to the page component as props
  }
}